# Generated by Django 5.0.6 on 2025-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash_pending',
            field=models.BooleanField(default=False),
        ),
    ]
